-- 001_initial_schema.sql
--
-- Foundations every later migration depends on: the UUID generator, the shared
-- updated_at trigger, and the enumerated types that model the product's fixed
-- vocabularies.
--
-- Naming conventions established here and followed throughout:
--   · tables and columns are snake_case, so no SQL needs double quotes
--   · primary keys are UUID, generated by the database
--   · every real point in time is TIMESTAMPTZ, never a naive timestamp
--   · tenant-owned tables carry organization_id and cascade from organizations
--   · natural keys are unique WITHIN an organisation, never globally

-- gen_random_uuid() lives in pgcrypto on PostgreSQL 12; it is built in from 13
-- onwards. Creating the extension is harmless on newer versions and required
-- on older ones, so it is done explicitly rather than assumed.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared trigger: keep updated_at honest
--
-- Application code can forget to set updated_at; a trigger cannot. Every table
-- with an updated_at column attaches this.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Enumerated types
--
-- These are closed sets the application already treats as exhaustive. Using
-- native enums rather than free text means the database rejects a value the
-- code does not understand, and a typo fails on write instead of producing a
-- row nothing can interpret.
--
-- Adding a value later is `ALTER TYPE ... ADD VALUE` in its own migration.
-- ---------------------------------------------------------------------------

CREATE TYPE organization_plan AS ENUM ('FREE', 'STARTER', 'GROWTH', 'ENTERPRISE');

CREATE TYPE user_role AS ENUM ('OWNER', 'ADMIN', 'HR', 'MANAGER', 'EMPLOYEE');

CREATE TYPE user_status AS ENUM ('ACTIVE', 'INVITED', 'DISABLED');

-- How an identity was established. Present from the start so that attaching a
-- real identity provider later needs no schema change — authentication itself
-- is intentionally deferred.
CREATE TYPE auth_provider AS ENUM ('DEV', 'PASSWORD', 'OTP', 'GOOGLE', 'MICROSOFT', 'SSO');

CREATE TYPE employee_status AS ENUM ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'SUSPENDED');

CREATE TYPE employment_type AS ENUM ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN', 'CONSULTANT');

CREATE TYPE office_status AS ENUM ('ACTIVE', 'INACTIVE');

CREATE TYPE attendance_status AS ENUM (
    'PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY', 'WEEKEND'
);

CREATE TYPE attendance_event_type AS ENUM ('CHECK_IN', 'CHECK_OUT', 'BREAK_START', 'BREAK_END');

-- The server's verdict on a submitted coordinate. Never supplied by a client:
-- the browser sends coordinates, the server decides which of these applies.
CREATE TYPE location_verification AS ENUM (
    'VERIFIED',
    'OUTSIDE_GEOFENCE',
    'LOW_ACCURACY',
    'NO_LOCATION',
    'SUSPECTED_SPOOF',
    'MANUAL_OVERRIDE'
);

CREATE TYPE attendance_source AS ENUM ('WEB', 'MOBILE', 'KIOSK', 'MANUAL', 'SYSTEM');

CREATE TYPE task_status AS ENUM ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETED', 'BLOCKED');

CREATE TYPE task_priority AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');

CREATE TYPE task_activity_type AS ENUM (
    'CREATED',
    'UPDATED',
    'STATUS_CHANGED',
    'PRIORITY_CHANGED',
    'ASSIGNED',
    'UNASSIGNED',
    'PROGRESS_UPDATED',
    'COMMENTED',
    'ATTACHMENT_ADDED',
    'SUBTASK_ADDED',
    'SUBTASK_COMPLETED',
    'DUE_DATE_CHANGED',
    'COMPLETED',
    'REOPENED'
);

CREATE TYPE leave_type AS ENUM (
    'CASUAL', 'SICK', 'EARNED', 'UNPAID', 'MATERNITY', 'PATERNITY', 'COMP_OFF'
);

CREATE TYPE leave_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

CREATE TYPE notification_type AS ENUM (
    'TASK_ASSIGNED',
    'TASK_DUE_SOON',
    'TASK_OVERDUE',
    'TASK_COMPLETED',
    'TASK_COMMENT',
    'ATTENDANCE_REMINDER',
    'LATE_ARRIVAL',
    'MISSED_CHECKOUT',
    'LEAVE_REQUESTED',
    'LEAVE_APPROVED',
    'LEAVE_REJECTED',
    'ANNOUNCEMENT',
    'GEOFENCE_ALERT'
);

CREATE TYPE notification_channel AS ENUM ('IN_APP', 'EMAIL', 'PUSH');

CREATE TYPE audit_action AS ENUM (
    'CREATE',
    'UPDATE',
    'DELETE',
    'LOGIN',
    'LOGOUT',
    'PERMISSION_CHANGE',
    'GEOFENCE_CHANGE',
    'ATTENDANCE_OVERRIDE',
    'EXPORT'
);
